version: "3.8"

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: pais
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secure123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./mohinirajagro
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: pais
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: secure123
      DATABASE_SSL: "false"
      NODE_ENV: production
    ports:
      - "1337:1337"
    depends_on:
      - db

  frontend:
    build: ./mohiniragagrofontend
    ports:
      - "5174:80"
    depends_on:
      - backend

volumes:
  pgdata: